### ISSUE TITLE
shallow_clone default causing difficulty with newer versions of git

### ISSUE THREAD

**Issue by benatkin** [poise/application#50]
I experienced the same issue as #49, but it isn't specific to Ubuntu, but is caused by using a newer version of git.

In order to sync a different branch than the one that is checked out I had to set `shallow_clone` to `false` before checking it out (on my existing node I deleted `cached_copy` to ensure that this happened when I ran `chef-client`).

When `shallow_clone` is not set to `false`, it can't sync to a revision that isn't merged to the revision that's checked out (in this case it's master).

On the `deploy` cookbook, `shallow_clone` defaults to `false`. I think it would be easier to use this `application` cookbook with newer distros if `shallow_clone` also defaulted to `false`.

**Comment by coderanger** [comment]
Released version 4.1.6 to supermarket.
