### ISSUE TITLE
[Chef 12.0] Cannot find a provider for deploy_revision[application] on ubuntu version 12.04

### ISSUE THREAD

**Issue by marcoamorales** [poise/application#53]
This looks to be related with the changes in Chef 12 regarding recipe DSL and providers.
```
================================================================================       
  Error executing action `deploy` on resource 'deploy_revision[nodejs application]'       
  ================================================================================       
         
  ArgumentError       
  -------------       
  Cannot find a provider for deploy_revision[nodejs application] on ubuntu version 12.04       
         
  Cookbook Trace:       
  ---------------       
  /tmp/kitchen/cache/cookbooks/application/libraries/default.rb:144:in `deploy_provider'       
  /tmp/kitchen/cache/cookbooks/application/libraries/default.rb:152:in `release_path'       
  /tmp/kitchen/cache/cookbooks/nodestack/recipes/application_nodejs.rb:93:in `block (3 levels) in from_file'       
  /tmp/kitchen/cache/cookbooks/application/libraries/default.rb:189:in `safe_recipe_eval'       
         /tmp/kitchen/cache/cookbooks/application/libraries/default.rb:165:in `callback'
         /tmp/kitchen/cache/cookbooks/application/providers/default.rb:193:in `run_actions_with_context'
         /tmp/kitchen/cache/cookbooks/application/providers/default.rb:172:in `block (2 levels) in run_deploy'
```

**Comment by martinb3** [comment]
:+1: wondering how to proceed. This is my last blocker on chef 12.

**Comment by Chili-Man** [comment]
I was starting to migrate to Chef 12 but then ran into this issue as well

**Comment by andybear** [comment]
This is currently blocking my entire deployment. Any idea how I can fix this on my own?

**Comment by mrloop** [comment]
@andybear use fork with a fix, e.g. in your Berksfile

```ruby
cookbook 'application', git: 'git@github.com:kangguru/application.git', ref: 'f7fc8797d789856a389adbe6f33647e3f5ad4ca9'
```

**Comment by martinb3** [comment]
@coderanger Can we help in any way, or get this commit merged in to master? https://github.com/kangguru/application/commit/f7fc8797d789856a389adbe6f33647e3f5ad4ca9

**Comment by coderanger** [comment]
Yes, will be merging this over and doing a release before I launch in to the upgrade work.

**Comment by martinb3** [comment]
:tada: :balloon: :birthday: :gift:

**Comment by coderanger** [comment]
Got to have the one last "lol legacy" release for people that can't upgrade easily >_<

**Comment by jujugrrr** [comment]
Hi @coderanger , just noticed you changed some tests, any news on this issue? We will rollback to chef 11 otherwise :-(

**Comment by coderanger** [comment]
@jujugrrr Getting regression tests in place before I merge the fix.

**Comment by coderanger** [comment]
Travis tells me things are happy!

**Comment by coderanger** [comment]
Released version 4.1.6 to supermarket.

**Comment by zgchurch** [comment]
You're the best. Thanks!

**Comment by jujugrrr** [comment]
cheers!

**Comment by shaneramey** [comment]
application_python has in its metadata.rb
`depends "application", "~> 3.0"`

This fix wasn't applied to the 3.x cookbook, so application_python is broke on Chef 12 until https://github.com/poise/application/commit/85f92b0bb0fbf2dfbabc93b6bafa63d9db121f83 is applied to 3.x
