### ISSUE TITLE
Faster deployments with git-based approach

### ISSUE THREAD

**Issue by Fodoj** [poise/application#54]
There is a better (== much faster) approach do deploying, using git tags, instead of releases directories. See more here http://blog.codeclimate.com/blog/2013/10/02/high-speed-rails-deploys-with-git/ and here http://factore.ca/blog/278-how-we-reduced-rails-deploy-times-to-under-one-second-with-plain-git

Are there any plans or thoughts on implementing this approach? Currently I hacked around with this small utility method:

```ruby
def files_changed?(repository, path_to_previous_revision, files)
  `cd #{repository} && git log HEAD...$(cat #{path_to_previous_revision}) -- #{files} | wc -l`.to_i > 0
end
```

that is then used in deployment callbacks as `only_if` guard. But it's kind of messy and still, it's not really git-tags solution. What do you think about?

**Comment by coderanger** [comment]
This is basically how things work now with application_git.
