### ISSUE TITLE
How do you use this cookbook?

### ISSUE THREAD

**Issue by JoeReid-Korrelate** [poise/application#57]
Hey Noah,

Big fan of your blog, man.

I know this cookbook is in the middle of a rewrite.  I've been following posting and github issues for both this project and the application_ruby cookbook over the last month or so, and I'm still not seeing much about how to USE these new cookbooks.  

Any ETA on when the project will be complete?   Do you need any help writing docs?

Regards,
Joe Reid

**Comment by coderanger** [comment]
I wrote up a guide for poise-service when I announced it on the mailing list that will work here too (applies to all Halite cookbooks).

In your Gemfile:

```ruby
gem 'halite', github: 'coderanger/halite'
gem 'poise', github: 'poise/poise'
gem 'poise-application', github: 'poise/application'
gem 'poise-boiler', github: 'poise/poise-boiler'
gem 'poise-service, github: 'poise/poise-service'
```

And then in your Berksfile:

```ruby
extension 'halite'
cookbook 'application', gem: 'poise-application'
cookbook 'poise-service', gem: 'poise-service'
```

I've not put docs in each of the cookbooks as this will only be needed before I cut a formal release, at that point you will get them from Supermarket like normal. As for the actual resources, either check out the code or take a look at the integration tests. So far the only plugins that are done are Git and Ruby (sans Rails and Passenger).

**Comment by JoeReid-Korrelate** [comment]
Right on, thanks.  I'll start playing around with that locally in Test Kitchen.

Quick follow up:  Any rough ETA on the formal release?  I know it's hard to estimate work in progress.  But are you thinking it will be done by end of April?  End of June?  Just looking for a guesstimate.

**Comment by coderanger** [comment]
I've got a storm of conferences for basically all of April (ChefConf and PyCon) so give or take reduced output during those I've got probably another 4 weeks of dev work left on Kickstarter-related stuff.
