### ISSUE TITLE
Guideline request - difference from artifact-cookbook and deploy_revision

### ISSUE THREAD

**Issue by eric-tucker** [poise/application#59]
I'm trying to find out how this cookbook differs (or overlaps) with the artifact-cookbook and the Chef built in deploy_revision logic.

Can you provide a bit of explanation please?

I want to move towards a managed LWRP setup for deploying packaged code or binary distributions (such as WAR files) and so far I've done all of the work manually (eg copying files around, cleaning up releases myself, updating symlinks myself, etc).  I'd like to know how to choose which cookbook to use.

**Comment by coderanger** [comment]
The `deploy` resource in core Chef is a re-implementation of the Capistrano deploy logic for the most part. It uses the cap folder layout and uses kinda-sorta callbacks to different stages of the deploy. The `artifact_file` resource isn't specifically built on top of `deploy` (I think at least) but it does inherit a lot of the philosophy. Both are relatively focused on getting the code deployed from a specific source (git/svn for `deploy`, Nexus/S3 for `artifact_file`) with the rest of the deploy logic in those callbacks. The `application` resource and related cookbooks stick to a more declarative approach like normal Chef recipes with different pieces of the deploy logic placed in sub-resources that maintain their own idempotent state. There are also pre-built deploy routines for things like Rails and Django, as well as deeper integration with service management via `poise-service`.

**Comment by eric-tucker** [comment]
Thanks for the notes.  That helps.  However, I will point out that the artifact cookbook does have an artifact_deploy resource that seems to do a lot of the plumbing of deploying a revision along with appropriate callbacks and hooks:

https://github.com/RiotGamesCookbooks/artifact-cookbook#artifact_deploy

Can you comment on how application is better?  From the sounds of it, application is done in a more "Chef way", but artifact_deploy seems to have a lot more input to customize the resource call.  Perhaps that's why it's not the "best" approach.

**Comment by coderanger** [comment]
I kind of lumped those together in my summary. `artifact_file` just does the download and could be used with the `application_*` structure. `artifact_deploy` is the thing that is like the core `deploy` resource in terms of a callback based workflow instead of more traditional idempotence. It is workable, but that API can be frustrating to work with as Chef is built for declarative, idempotent resources not procedural callbacks.

**Comment by eric-tucker** [comment]
OK.  So it sounds like this cookbook is more Chef like so I should probably stick to this one when possible.  Thanks!

**Comment by coderanger** [comment]
Heh, both have their advantages, if you want a workflow that is really close to the Riot one then theirs might be easier, I would like to think the Application cookbook framework/whatever is more flexible in the long run.
