### ISSUE TITLE
unable to deploy rails application

### ISSUE THREAD

**Issue by lylianmeyemezu** [poise/application#60]
Hi,
I have been attempting to setup a chef recipe which installs ruby using bundle_install and then uses the application_ruby cookbook to configure the application.
I have the following error : 
NameError : No resource found for bundle install

**Comment by coderanger** [comment]
Please include the actual recipe text. Also make sure you are using the master branch versions, not the old release.

**Comment by lylianmeyemezu** [comment]
Hi,
thanks for replying.
this is my recipe file 
# encoding: UTF-8
#
# Cookbook Name:: sd2-application
# Recipe:: default
#
# Copyright (C) 2015 YOUR_NAME
#
# All rights reserved - Do Not Redistribute
#
# we define our application using application resource provided by application
application '/opt/sd2-application' do
  path '/opt/sd2-application'
  owner 'sd2'
  group 'sd2'

  repository 'https://github.com/SelfDeploy/selfdeploy2.git'
  revision 'master'
  deploy_key 'xxxxxx'
'
  bundle_install do
    deployment true
  end  
  # Apply the rails LWRP from application_ruby
  rails do
    # Rails-specific configuration. See the README in the
    # application_ruby cookbook for more information.
    name 'sd2-application'
    ruby '2.2.3'
    ruby_gem 'rake'
    ruby_execute 'rake'
    bundle_install do
      deployment true
      without %w(development test)
    end

    database do
      adapter 'sqlite3'
      database 'db/production.sqlite3'
      migrate false
    end

    thin do
      service_name 'Selfdeploy2'
      port 8080
    end
  end
end

**Comment by coderanger** [comment]
So two issues: first you have the git parameters directly in the `application` resource, those need to be in an `application_git` resource. Second, make sure you have `application_git` and `application_ruby` in the metadata.rb dependencies for `sd2-application`, along with the required code to pull them in from master versions.

**Comment by lylianmeyemezu** [comment]
Hi,
Thanks for replying.
I updated metadata.rb file with application_git. I got Unable to satisfy constraints on package application_git, which does not exist
I manually download application_git cookbook and add cookbook 'application_git', path: '../application_git' to Berksfile, i add the same error.
Could you give a working example of an application .rb file and a metadata.rb ?
Thanks a lot for your help.
Regards

**Comment by coderanger** [comment]
You can find an example over in https://github.com/poise/application_examples/

**Comment by coderanger** [comment]
Closing this out now that all the required cookbooks are available via normal Supermarket downloads.
