### ISSUE TITLE
path is not the "name-attribute" anymore

### ISSUE THREAD

**Issue by computerlyrik** [poise/application#61]
Got this error with latest supermarket version:

```
    ArgumentError
    -------------
    You must supply a name when declaring a directory resource
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/application/providers/default.rb:75:in `before_deploy'
    /var/chef/cache/cookbooks/application/providers/default.rb:27:in `block in class_from_file
```

Please update documentation.

fix by setting ```path``` attribute explicitly

**Comment by coderanger** [comment]
Please include your recipe code as well.

**Comment by coderanger** [comment]
Never mind, I can tell from the traceback that you are using the old 4.x application cookbook which is not supported with newer Chef.
