### ISSUE TITLE
Status of this cookbook/documentation

### ISSUE THREAD

**Issue by onknows** [poise/application#64]
This cookbook looks comprehensive but is no longer maintained? Or is the documentation not up-to-date? I noticed that many of the examples don't work. For example snippet below does not work. `git` needs to be `path`. And `bundle_install` is not a resource!? `unicorn` also does not exist!?

```
application '/opt/test_sinatra' do
  git 'https://github.com/example/my_sinatra_app.git'
  bundle_install do
    deployment true
  end
  unicorn do
    port 9000
  end
end
```

**Comment by coderanger** [comment]
The examples are using resources from the `application_git` and `application_ruby` cookbooks. This cookbook just provides the core framework and mixins used by the others. You can find links to all of them right below the examples section. If you're looking for examples that run out of the box check out the `application_examples` cookbook.
